### ISSUE TITLE
About filtering strategy for pseudo labels

### ISSUE THREAD

**Issue by gavinwxy** [xmed-lab/AllSpark#1]
Hi, thanks for your inspiring work. I notice that there is no quality control on pseudo labels. How is that possible to guarantee the training quality. I am also surprised that no cutmix augmentation is used in your work. Can you shed some light on how allspark can achieve such good performance without label filtering and strong augmentation?

**Comment by McGregorWwww** [comment]
Hi, thanks for your interest of our work.

The reason why AllSpark works well without quality control on pseudo labels and advanced augmentations is that compared to previous work which mainly focus on how to improve the training of unlabeled data, we focus more on the labeled training process. In other words, we try to make sure the training of labeled data flow performs well under diverse representations of the unlabeled data. Thus, the function of the pseudo-labeling scheme in our framework can be seen as a guarantee of feature quality of unlabeled data rather than the pseudo label quality.

Furthermore, as can be seen in the paper, we use a very basic pseudo-labeling baseline to highlight the superiority of the AllSpark module, which means the performance can be further improved by integrating traditional methods that improve the pseudo labels or using stronger augmentation techniques.

Hope this helps for better understanding.

**Comment by gavinwxy** [comment]
Thanks for your reply.
